# Generated by Django 5.2.1 on 2025-06-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='finance.transactionaccount'),
        ),
    ]
