# Generated by Django 5.2.1 on 2025-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('TR', 'Transfer')], max_length=2),
        ),
    ]
