# Generated by Django 5.2.1 on 2025-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transactionaccount_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionaccount',
            name='color',
            field=models.CharField(default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='color',
            field=models.CharField(default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome class e.g. fa-solid fa-utensils', max_length=50),
        ),
    ]
