---
name: ✨ Feature Request
about: Suggest a new feature or improvement
title: "[FEATURE] "
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem?**
A clear and concise description of the problem you're trying to solve.

**Describe the solution you'd like**
What would you like to happen? Describe the ideal implementation.

**Describe alternatives you've considered**
Any alternative solutions or features you've thought about?

**Additional context**
Add any other context, mockups, or references here.
